/**
 * API INTEGRATION SCHEMA
 * Complete documentation for backend API endpoints
 * 
 * This file defines all API contracts between frontend and backend.
 * Backend developers should implement these exact interfaces.
 * 
 * ⚠️ CRITICAL IMAGE GENERATION REQUIREMENT ⚠️
 * ALL tattoo images generated by the backend MUST be:
 * - PNG format with alpha channel (transparent background)
 * - Minimum 512x512px, Maximum 2048x2048px  
 * - NO white/colored backgrounds - transparency is REQUIRED
 * - This is non-negotiable for tattoo mockups and professional use
 */

/**
 * ============================================================
 * ASK TaTTTy AI ENDPOINTS
 * ============================================================
 */

/**
 * ENDPOINT: POST /api/ai/enhance
 * 
 * PURPOSE: Enhance user's text with AI suggestions
 * - Makes text more descriptive and detailed
 * - Adds style-specific terminology
 * - Optimizes for tattoo design clarity
 */
export interface EnhanceTextRequest {
  /** Type of enhancement requested */
  type: 'enhance';
  
  /** Context for the enhancement (affects AI's approach) */
  contextType: 'couples' | 'coverup' | 'extend' | 'tattty' | 'freestyle' | 'weird' | 'general';
  
  /** The text to enhance */
  targetText: string;
  
  /** Whether this text is a selected portion or full text */
  hasSelection: boolean;
}

export interface EnhanceTextResponse {
  /** Enhanced text result */
  result: string;
  
  /** Optional: Original text for reference */
  original?: string;
}

/**
 * STREAMING RESPONSE FORMAT (Server-Sent Events)
 * 
 * If implementing streaming, send chunks as:
 * 
 * data: {"token": "chunk of text"}
 * data: {"token": " more text"}
 * data: {"done": true}
 * 
 * Content-Type: text/event-stream
 */

/**
 * ENDPOINT: POST /api/ai/ideas
 * 
 * PURPOSE: Generate creative tattoo ideas
 * - Provides fresh design suggestions
 * - Context-aware recommendations
 * - Can work with or without existing text
 */
export interface GenerateIdeasRequest {
  /** Type of generation requested */
  type: 'ideas';
  
  /** Context for idea generation */
  contextType: 'couples' | 'coverup' | 'extend' | 'tattty' | 'freestyle' | 'weird' | 'general';
  
  /** Optional: Current text for context (can be empty) */
  targetText: string;
  
  /** Whether this text is a selected portion or full text */
  hasSelection: boolean;
}

export interface GenerateIdeasResponse {
  /** Generated ideas text */
  result: string;
}

/**
 * ============================================================
 * ERROR RESPONSES
 * ============================================================
 */

export interface APIErrorResponse {
  /** Error message to display to user */
  error: string;
  
  /** Optional: Error code for debugging */
  code?: string;
  
  /** Optional: Additional details */
  details?: string;
}

/**
 * ============================================================
 * CONTEXT TYPE DESCRIPTIONS
 * ============================================================
 */

export const CONTEXT_DESCRIPTIONS = {
  tattty: 'Main TaTTTy generator - two questions format with style options',
  freestyle: 'Freestyle generator - single creative prompt with optional constraints',
  couples: 'Couple tattoos - matching or complementary designs',
  coverup: 'Cover-up designs - hiding existing tattoos',
  extend: 'Extending existing tattoos - adding to current designs',
  weird: 'Experimental/surreal designs - unconventional requests',
  general: 'General purpose - no specific context',
};

/**
 * ============================================================
 * IMPLEMENTATION NOTES FOR BACKEND
 * ============================================================
 */

/**
 * REQUEST VALIDATION:
 * - targetText: No minimum length for 'ideas', 10+ chars for 'enhance'
 * - contextType: Must be one of the valid context types
 * - type: Must be either 'enhance' or 'ideas'
 */

/**
 * RESPONSE TIME EXPECTATIONS:
 * - Non-streaming: 2-5 seconds max
 * - Streaming: First token within 1 second, complete within 10 seconds
 * - Timeout: Frontend will abort after 30 seconds
 */

/**
 * STREAMING BEST PRACTICES:
 * - Send tokens in chunks of 3-5 words
 * - Include proper SSE format: "data: {json}\n\n"
 * - Send final chunk with {"done": true}
 * - Set Content-Type: text/event-stream
 * - Enable CORS for streaming
 */

/**
 * ERROR HANDLING:
 * - 400: Bad request (invalid contextType, missing fields)
 * - 429: Rate limit exceeded
 * - 500: AI service error
 * - 503: Service temporarily unavailable
 */

/**
 * ============================================================
 * EXAMPLE IMPLEMENTATIONS
 * ============================================================
 */

/** 
 * Example non-streaming response:
 * 
 * HTTP/1.1 200 OK
 * Content-Type: application/json
 * 
 * {
 *   "result": "A majestic dragon wrapping around your forearm..."
 * }
 */

/**
 * Example streaming response:
 * 
 * HTTP/1.1 200 OK
 * Content-Type: text/event-stream
 * 
 * data: {"token": "A majestic"}
 * 
 * data: {"token": " dragon wrapping"}
 * 
 * data: {"token": " around your forearm..."}
 * 
 * data: {"done": true}
 * 
 */

/**
 * Example error response:
 * 
 * HTTP/1.1 400 Bad Request
 * Content-Type: application/json
 * 
 * {
 *   "error": "Text too short for enhancement",
 *   "code": "VALIDATION_ERROR",
 *   "details": "Minimum 10 characters required"
 * }
 */

/**
 * ============================================================
 * FRONTEND USAGE
 * ============================================================
 */

/**
 * Frontend makes requests from:
 * - AskTaTTTy component (/components/shared/AskTaTTTy.tsx)
 * 
 * Environment variable:
 * - VITE_API_URL: Base URL for API (e.g., "https://api.tatty.com")
 * 
 * Full endpoint URLs:
 * - ${VITE_API_URL}/api/ai/enhance
 * - ${VITE_API_URL}/api/ai/ideas
 */

/**
 * ============================================================
 * TESTING CHECKLIST
 * ============================================================
 */

export const API_TESTING_CHECKLIST = {
  enhance: [
    '✓ Accepts valid enhance request',
    '✓ Returns enhanced text within 5 seconds',
    '✓ Handles empty/short text gracefully',
    '✓ Works with all contextType values',
    '✓ Streaming works (if implemented)',
    '✓ Error responses are user-friendly',
  ],
  ideas: [
    '✓ Accepts valid ideas request',
    '✓ Returns ideas within 5 seconds',
    '✓ Works with empty targetText',
    '✓ Context-aware suggestions',
    '✓ Streaming works (if implemented)',
    '✓ Error responses are user-friendly',
  ],
  general: [
    '✓ CORS headers set correctly',
    '✓ Rate limiting implemented',
    '✓ Timeout handling (30s)',
    '✓ Proper error codes (400, 429, 500, 503)',
    '✓ Request logging for debugging',
  ],
};
